import common

type
    Hint* = enum
        AllowAltTabWhileGrabbed            = "SDL_ALLOW_ALT_TAB_WHILE_GRABBED"
        AndroidAllowRecreateActivity       = "SDL_ANDROID_ALLOW_RECREATE_ACTIVITY"
        AndroidBlockOnPause                = "SDL_ANDROID_BLOCK_ON_PAUSE"
        AndroidLowLatencyAudio             = "SDL_ANDROID_LOW_LATENCY_AUDIO"
        AndroidTrapBackButton              = "SDL_ANDROID_TRAP_BACK_BUTTON"
        AppId                              = "SDL_APP_ID"
        AppName                            = "SDL_APP_NAME"
        AppleTvControllerUIEvents          = "SDL_APPLE_TV_CONTROLLER_UI_EVENTS"
        AppleTvRemoteAllowRotation         = "SDL_APPLE_TV_REMOTE_ALLOW_ROTATION"
        AudioAlsaDefaultDevice             = "SDL_AUDIO_ALSA_DEFAULT_DEVICE"
        AudioAlsaDefaultPlaybackDevice     = "SDL_AUDIO_ALSA_DEFAULT_PLAYBACK_DEVICE"
        AudioAlsaDefaultRecordingDevice    = "SDL_AUDIO_ALSA_DEFAULT_RECORDING_DEVICE"
        AudioCategory                      = "SDL_AUDIO_CATEGORY"
        AudioChannels                      = "SDL_AUDIO_CHANNELS"
        AudioDeviceAppIconName             = "SDL_AUDIO_DEVICE_APP_ICON_NAME"
        AudioDeviceSampleFrames            = "SDL_AUDIO_DEVICE_SAMPLE_FRAMES"
        AudioDeviceStreamName              = "SDL_AUDIO_DEVICE_STREAM_NAME"
        AudioDeviceStreamRole              = "SDL_AUDIO_DEVICE_STREAM_ROLE"
        AudioDiskInputFile                 = "SDL_AUDIO_DISK_INPUT_FILE"
        AudioDiskOutputFile                = "SDL_AUDIO_DISK_OUTPUT_FILE"
        AudioDiskTimescale                 = "SDL_AUDIO_DISK_TIMESCALE"
        AudioDriver                        = "SDL_AUDIO_DRIVER"
        AudioDummyTimescale                = "SDL_AUDIO_DUMMY_TIMESCALE"
        AudioFormat                        = "SDL_AUDIO_FORMAT"
        AudioFrequency                     = "SDL_AUDIO_FREQUENCY"
        AudioIncludeMonitors               = "SDL_AUDIO_INCLUDE_MONITORS"
        AutoUpdateJoysticks                = "SDL_AUTO_UPDATE_JOYSTICKS"
        AutoUpdateSensors                  = "SDL_AUTO_UPDATE_SENSORS"
        BmpSaveLegacyFormat                = "SDL_BMP_SAVE_LEGACY_FORMAT"
        CameraDriver                       = "SDL_CAMERA_DRIVER"
        CpuFeatureMask                     = "SDL_CPU_FEATURE_MASK"
        JoystickDirectinput                = "SDL_JOYSTICK_DIRECTINPUT"
        FileDialogDriver                   = "SDL_FILE_DIALOG_DRIVER"
        DisplayUsableBounds                = "SDL_DISPLAY_USABLE_BOUNDS"
        EmscriptenAsyncify                 = "SDL_EMSCRIPTEN_ASYNCIFY"
        EmscriptenCanvasSelector           = "SDL_EMSCRIPTEN_CANVAS_SELECTOR"
        EmscriptenKeyboardElement          = "SDL_EMSCRIPTEN_KEYBOARD_ELEMENT"
        EnableScreenKeyboard               = "SDL_ENABLE_SCREEN_KEYBOARD"
        EvdevDevices                       = "SDL_EVDEV_DEVICES"
        EventLogging                       = "SDL_EVENT_LOGGING"
        ForceRaisewindow                   = "SDL_FORCE_RAISEWINDOW"
        FramebufferAcceleration            = "SDL_FRAMEBUFFER_ACCELERATION"
        Gamecontrollerconfig               = "SDL_GAMECONTROLLERCONFIG"
        GamecontrollerconfigFile           = "SDL_GAMECONTROLLERCONFIG_FILE"
        Gamecontrollertype                 = "SDL_GAMECONTROLLERTYPE"
        GamecontrollerIgnoreDevices        = "SDL_GAMECONTROLLER_IGNORE_DEVICES"
        GamecontrollerIgnoreDevicesExcept  = "SDL_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT"
        GamecontrollerSensorFusion         = "SDL_GAMECONTROLLER_SENSOR_FUSION"
        GdkTextinputDefaultText            = "SDL_GDK_TEXTINPUT_DEFAULT_TEXT"
        GdkTextinputDescription            = "SDL_GDK_TEXTINPUT_DESCRIPTION"
        GdkTextinputMaxLength              = "SDL_GDK_TEXTINPUT_MAX_LENGTH"
        GdkTextinputScope                  = "SDL_GDK_TEXTINPUT_SCOPE"
        GdkTextinputTitle                  = "SDL_GDK_TEXTINPUT_TITLE"
        HidapiLibusb                       = "SDL_HIDAPI_LIBUSB"
        HidapiLibusbWhitelist              = "SDL_HIDAPI_LIBUSB_WHITELIST"
        HidapiUdev                         = "SDL_HIDAPI_UDEV"
        GpuDriver                          = "SDL_GPU_DRIVER"
        HidapiEnumerateOnlyControllers     = "SDL_HIDAPI_ENUMERATE_ONLY_CONTROLLERS"
        HidapiIgnoreDevices                = "SDL_HIDAPI_IGNORE_DEVICES"
        ImeImplementedUI                   = "SDL_IME_IMPLEMENTED_UI"
        IosHideHomeIndicator               = "SDL_IOS_HIDE_HOME_INDICATOR"
        JoystickAllowBackgroundEvents      = "SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS"
        JoystickArcadestickDevices         = "SDL_JOYSTICK_ARCADESTICK_DEVICES"
        JoystickArcadestickDevicesExcluded = "SDL_JOYSTICK_ARCADESTICK_DEVICES_EXCLUDED"
        JoystickBlacklistDevices           = "SDL_JOYSTICK_BLACKLIST_DEVICES"
        JoystickBlacklistDevicesExcluded   = "SDL_JOYSTICK_BLACKLIST_DEVICES_EXCLUDED"
        JoystickDevice                     = "SDL_JOYSTICK_DEVICE"
        JoystickEnhancedReports            = "SDL_JOYSTICK_ENHANCED_REPORTS"
        JoystickFlightstickDevices         = "SDL_JOYSTICK_FLIGHTSTICK_DEVICES"
        JoystickFlightstickDevicesExcluded = "SDL_JOYSTICK_FLIGHTSTICK_DEVICES_EXCLUDED"
        JoystickGameinput                  = "SDL_JOYSTICK_GAMEINPUT"
        JoystickGamecubeDevices            = "SDL_JOYSTICK_GAMECUBE_DEVICES"
        JoystickGamecubeDevicesExcluded    = "SDL_JOYSTICK_GAMECUBE_DEVICES_EXCLUDED"
        JoystickHidapi                     = "SDL_JOYSTICK_HIDAPI"
        JoystickHidapiCombineJoyCons       = "SDL_JOYSTICK_HIDAPI_COMBINE_JOY_CONS"
        JoystickHidapiGamecube             = "SDL_JOYSTICK_HIDAPI_GAMECUBE"
        JoystickHidapiGamecubeRumbleBrake  = "SDL_JOYSTICK_HIDAPI_GAMECUBE_RUMBLE_BRAKE"
        JoystickHidapiJoyCons              = "SDL_JOYSTICK_HIDAPI_JOY_CONS"
        JoystickHidapiJoyconHomeLed        = "SDL_JOYSTICK_HIDAPI_JOYCON_HOME_LED"
        JoystickHidapiLuna                 = "SDL_JOYSTICK_HIDAPI_LUNA"
        JoystickHidapiNintendoClassic      = "SDL_JOYSTICK_HIDAPI_NINTENDO_CLASSIC"
        JoystickHidapiPs3                  = "SDL_JOYSTICK_HIDAPI_PS3"
        JoystickHidapiPs3SixaxisDriver     = "SDL_JOYSTICK_HIDAPI_PS3_SIXAXIS_DRIVER"
        JoystickHidapiPs4                  = "SDL_JOYSTICK_HIDAPI_PS4"
        JoystickHidapiPs4ReportInterval    = "SDL_JOYSTICK_HIDAPI_PS4_REPORT_INTERVAL"
        JoystickHidapiPs5                  = "SDL_JOYSTICK_HIDAPI_PS5"
        JoystickHidapiPs5PlayerLed         = "SDL_JOYSTICK_HIDAPI_PS5_PLAYER_LED"
        JoystickHidapiShield               = "SDL_JOYSTICK_HIDAPI_SHIELD"
        JoystickHidapiStadia               = "SDL_JOYSTICK_HIDAPI_STADIA"
        JoystickHidapiSteam                = "SDL_JOYSTICK_HIDAPI_STEAM"
        JoystickHidapiSteamHomeLed         = "SDL_JOYSTICK_HIDAPI_STEAM_HOME_LED"
        JoystickHidapiSteamdeck            = "SDL_JOYSTICK_HIDAPI_STEAMDECK"
        JoystickHidapiSteamHori            = "SDL_JOYSTICK_HIDAPI_STEAM_HORI"
        JoystickHidapiSwitch               = "SDL_JOYSTICK_HIDAPI_SWITCH"
        JoystickHidapiSwitchHomeLed        = "SDL_JOYSTICK_HIDAPI_SWITCH_HOME_LED"
        JoystickHidapiSwitchPlayerLed      = "SDL_JOYSTICK_HIDAPI_SWITCH_PLAYER_LED"
        JoystickHidapiVerticalJoyCons      = "SDL_JOYSTICK_HIDAPI_VERTICAL_JOY_CONS"
        JoystickHidapiWii                  = "SDL_JOYSTICK_HIDAPI_WII"
        JoystickHidapiWiiPlayerLed         = "SDL_JOYSTICK_HIDAPI_WII_PLAYER_LED"
        JoystickHidapiXbox                 = "SDL_JOYSTICK_HIDAPI_XBOX"
        JoystickHidapiXbox360              = "SDL_JOYSTICK_HIDAPI_XBOX_360"
        JoystickHidapiXbox360PlayerLed     = "SDL_JOYSTICK_HIDAPI_XBOX_360_PLAYER_LED"
        JoystickHidapiXbox360Wireless      = "SDL_JOYSTICK_HIDAPI_XBOX_360_WIRELESS"
        JoystickHidapiXboxOne              = "SDL_JOYSTICK_HIDAPI_XBOX_ONE"
        JoystickHidapiXboxOneHomeLed       = "SDL_JOYSTICK_HIDAPI_XBOX_ONE_HOME_LED"
        JoystickIokit                      = "SDL_JOYSTICK_IOKIT"
        JoystickLinuxClassic               = "SDL_JOYSTICK_LINUX_CLASSIC"
        JoystickLinuxDeadzones             = "SDL_JOYSTICK_LINUX_DEADZONES"
        JoystickLinuxDigitalHats           = "SDL_JOYSTICK_LINUX_DIGITAL_HATS"
        JoystickLinuxHatDeadzones          = "SDL_JOYSTICK_LINUX_HAT_DEADZONES"
        JoystickMfi                        = "SDL_JOYSTICK_MFI"
        JoystickRawinput                   = "SDL_JOYSTICK_RAWINPUT"
        JoystickRawinputCorrelateXinput    = "SDL_JOYSTICK_RAWINPUT_CORRELATE_XINPUT"
        JoystickRogChakram                 = "SDL_JOYSTICK_ROG_CHAKRAM"
        JoystickThread                     = "SDL_JOYSTICK_THREAD"
        JoystickThrottleDevices            = "SDL_JOYSTICK_THROTTLE_DEVICES"
        JoystickThrottleDevicesExcluded    = "SDL_JOYSTICK_THROTTLE_DEVICES_EXCLUDED"
        JoystickWgi                        = "SDL_JOYSTICK_WGI"
        JoystickWheelDevices               = "SDL_JOYSTICK_WHEEL_DEVICES"
        JoystickWheelDevicesExcluded       = "SDL_JOYSTICK_WHEEL_DEVICES_EXCLUDED"
        JoystickZeroCenteredDevices        = "SDL_JOYSTICK_ZERO_CENTERED_DEVICES"
        JoystickHapticAxes                 = "SDL_JOYSTICK_HAPTIC_AXES"
        KeycodeOptions                     = "SDL_KEYCODE_OPTIONS"
        KmsdrmDeviceIndex                  = "SDL_KMSDRM_DEVICE_INDEX"
        KmsdrmRequireDrmMaster             = "SDL_KMSDRM_REQUIRE_DRM_MASTER"
        Logging                            = "SDL_LOGGING"
        MacBackgroundApp                   = "SDL_MAC_BACKGROUND_APP"
        MacCtrlClickEmulateRightClick      = "SDL_MAC_CTRL_CLICK_EMULATE_RIGHT_CLICK"
        MacOpenglAsyncDispatch             = "SDL_MAC_OPENGL_ASYNC_DISPATCH"
        MacOptionAsAlt                     = "SDL_MAC_OPTION_AS_ALT"
        MacScrollMomentum                  = "SDL_MAC_SCROLL_MOMENTUM"
        MainCallbackRate                   = "SDL_MAIN_CALLBACK_RATE"
        MouseAutoCapture                   = "SDL_MOUSE_AUTO_CAPTURE"
        MouseDoubleClickRadius             = "SDL_MOUSE_DOUBLE_CLICK_RADIUS"
        MouseDoubleClickTime               = "SDL_MOUSE_DOUBLE_CLICK_TIME"
        MouseDefaultSystemCursor           = "SDL_MOUSE_DEFAULT_SYSTEM_CURSOR"
        MouseEmulateWarpWithRelative       = "SDL_MOUSE_EMULATE_WARP_WITH_RELATIVE"
        MouseFocusClickthrough             = "SDL_MOUSE_FOCUS_CLICKTHROUGH"
        MouseNormalSpeedScale              = "SDL_MOUSE_NORMAL_SPEED_SCALE"
        MouseRelativeModeCenter            = "SDL_MOUSE_RELATIVE_MODE_CENTER"
        MouseRelativeSpeedScale            = "SDL_MOUSE_RELATIVE_SPEED_SCALE"
        MouseRelativeSystemScale           = "SDL_MOUSE_RELATIVE_SYSTEM_SCALE"
        MouseRelativeWarpMotion            = "SDL_MOUSE_RELATIVE_WARP_MOTION"
        MouseRelativeCursorVisible         = "SDL_MOUSE_RELATIVE_CURSOR_VISIBLE"
        MouseTouchEvents                   = "SDL_MOUSE_TOUCH_EVENTS"
        MuteConsoleKeyboard                = "SDL_MUTE_CONSOLE_KEYBOARD"
        NoSignalHandlers                   = "SDL_NO_SIGNAL_HANDLERS"
        OpenglLibrary                      = "SDL_OPENGL_LIBRARY"
        EglLibrary                         = "SDL_EGL_LIBRARY"
        OpenglEsDriver                     = "SDL_OPENGL_ES_DRIVER"
        OpenvrLibrary                      = "SDL_OPENVR_LIBRARY"
        Orientations                       = "SDL_ORIENTATIONS"
        PollSentinel                       = "SDL_POLL_SENTINEL"
        PreferredLocales                   = "SDL_PREFERRED_LOCALES"
        QuitOnLastWindowClose              = "SDL_QUIT_ON_LAST_WINDOW_CLOSE"
        RenderDirect3dThreadsafe           = "SDL_RENDER_DIRECT3D_THREADSAFE"
        RenderDirect3d11Debug              = "SDL_RENDER_DIRECT3D11_DEBUG"
        RenderVulkanDebug                  = "SDL_RENDER_VULKAN_DEBUG"
        RenderGpuDebug                     = "SDL_RENDER_GPU_DEBUG"
        RenderGpuLowPower                  = "SDL_RENDER_GPU_LOW_POWER"
        RenderDriver                       = "SDL_RENDER_DRIVER"
        RenderLineMethod                   = "SDL_RENDER_LINE_METHOD"
        RenderMetalPreferLowPowerDevice    = "SDL_RENDER_METAL_PREFER_LOW_POWER_DEVICE"
        RenderVsync                        = "SDL_RENDER_VSYNC"
        ReturnKeyHidesIme                  = "SDL_RETURN_KEY_HIDES_IME"
        RogGamepadMice                     = "SDL_ROG_GAMEPAD_MICE"
        RogGamepadMiceExcluded             = "SDL_ROG_GAMEPAD_MICE_EXCLUDED"
        RpiVideoLayer                      = "SDL_RPI_VIDEO_LAYER"
        ScreensaverInhibitActivityName     = "SDL_SCREENSAVER_INHIBIT_ACTIVITY_NAME"
        ShutdownDbusOnQuit                 = "SDL_SHUTDOWN_DBUS_ON_QUIT"
        StorageTitleDriver                 = "SDL_STORAGE_TITLE_DRIVER"
        StorageUserDriver                  = "SDL_STORAGE_USER_DRIVER"
        ThreadForceRealtimeTimeCritical    = "SDL_THREAD_FORCE_REALTIME_TIME_CRITICAL"
        ThreadPriorityPolicy               = "SDL_THREAD_PRIORITY_POLICY"
        TimerResolution                    = "SDL_TIMER_RESOLUTION"
        TouchMouseEvents                   = "SDL_TOUCH_MOUSE_EVENTS"
        TrackpadIsTouchOnly                = "SDL_TRACKPAD_IS_TOUCH_ONLY"
        TvRemoteAsJoystick                 = "SDL_TV_REMOTE_AS_JOYSTICK"
        VideoAllowScreensaver              = "SDL_VIDEO_ALLOW_SCREENSAVER"
        VideoDisplayPriority               = "SDL_VIDEO_DISPLAY_PRIORITY"
        VideoDoubleBuffer                  = "SDL_VIDEO_DOUBLE_BUFFER"
        VideoDriver                        = "SDL_VIDEO_DRIVER"
        VideoDummySaveFrames               = "SDL_VIDEO_DUMMY_SAVE_FRAMES"
        VideoEglAllowGetdisplayFallback    = "SDL_VIDEO_EGL_ALLOW_GETDISPLAY_FALLBACK"
        VideoForceEgl                      = "SDL_VIDEO_FORCE_EGL"
        VideoMacFullscreenSpaces           = "SDL_VIDEO_MAC_FULLSCREEN_SPACES"
        VideoMacFullscreenMenuVisibility   = "SDL_VIDEO_MAC_FULLSCREEN_MENU_VISIBILITY"
        VideoMinimizeOnFocusLoss           = "SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS"
        VideoOffscreenSaveFrames           = "SDL_VIDEO_OFFSCREEN_SAVE_FRAMES"
        VideoSyncWindowOperations          = "SDL_VIDEO_SYNC_WINDOW_OPERATIONS"
        VideoWaylandAllowLibdecor          = "SDL_VIDEO_WAYLAND_ALLOW_LIBDECOR"
        VideoWaylandModeEmulation          = "SDL_VIDEO_WAYLAND_MODE_EMULATION"
        VideoWaylandModeScaling            = "SDL_VIDEO_WAYLAND_MODE_SCALING"
        VideoWaylandPreferLibdecor         = "SDL_VIDEO_WAYLAND_PREFER_LIBDECOR"
        VideoWaylandScaleToDisplay         = "SDL_VIDEO_WAYLAND_SCALE_TO_DISPLAY"
        VideoWinD3dcompiler                = "SDL_VIDEO_WIN_D3DCOMPILER"
        VideoX11NetWmBypassCompositor      = "SDL_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR"
        VideoX11NetWmPing                  = "SDL_VIDEO_X11_NET_WM_PING"
        VideoX11Nodirectcolor              = "SDL_VIDEO_X11_NODIRECTCOLOR"
        VideoX11ScalingFactor              = "SDL_VIDEO_X11_SCALING_FACTOR"
        VideoX11Visualid                   = "SDL_VIDEO_X11_VISUALID"
        VideoX11WindowVisualid             = "SDL_VIDEO_X11_WINDOW_VISUALID"
        VideoX11Xrandr                     = "SDL_VIDEO_X11_XRANDR"
        VitaEnableBackTouch                = "SDL_VITA_ENABLE_BACK_TOUCH"
        VitaEnableFrontTouch               = "SDL_VITA_ENABLE_FRONT_TOUCH"
        VitaModulePath                     = "SDL_VITA_MODULE_PATH"
        VitaPvrInit                        = "SDL_VITA_PVR_INIT"
        VitaResolution                     = "SDL_VITA_RESOLUTION"
        VitaPvrOpengl                      = "SDL_VITA_PVR_OPENGL"
        VitaTouchMouseDevice               = "SDL_VITA_TOUCH_MOUSE_DEVICE"
        VulkanDisplay                      = "SDL_VULKAN_DISPLAY"
        VulkanLibrary                      = "SDL_VULKAN_LIBRARY"
        WaveFactChunk                      = "SDL_WAVE_FACT_CHUNK"
        WaveChunkLimit                     = "SDL_WAVE_CHUNK_LIMIT"
        WaveRiffChunkSize                  = "SDL_WAVE_RIFF_CHUNK_SIZE"
        WaveTruncation                     = "SDL_WAVE_TRUNCATION"
        WindowActivateWhenRaised           = "SDL_WINDOW_ACTIVATE_WHEN_RAISED"
        WindowActivateWhenShown            = "SDL_WINDOW_ACTIVATE_WHEN_SHOWN"
        WindowAllowTopmost                 = "SDL_WINDOW_ALLOW_TOPMOST"
        WindowFrameUsableWhileCursorHidden = "SDL_WINDOW_FRAME_USABLE_WHILE_CURSOR_HIDDEN"
        WindowsCloseOnAltF4                = "SDL_WINDOWS_CLOSE_ON_ALT_F4"
        WindowsEnableMenuMnemonics         = "SDL_WINDOWS_ENABLE_MENU_MNEMONICS"
        WindowsEnableMessageloop           = "SDL_WINDOWS_ENABLE_MESSAGELOOP"
        WindowsGameinput                   = "SDL_WINDOWS_GAMEINPUT"
        WindowsRawKeyboard                 = "SDL_WINDOWS_RAW_KEYBOARD"
        WindowsForceSemaphoreKernel        = "SDL_WINDOWS_FORCE_SEMAPHORE_KERNEL"
        WindowsIntresourceIcon             = "SDL_WINDOWS_INTRESOURCE_ICON"
        WindowsIntresourceIconSmall        = "SDL_WINDOWS_INTRESOURCE_ICON_SMALL"
        WindowsUseD3d9ex                   = "SDL_WINDOWS_USE_D3D9EX"
        WindowsEraseBackgroundMode         = "SDL_WINDOWS_ERASE_BACKGROUND_MODE"
        X11ForceOverrideRedirect           = "SDL_X11_FORCE_OVERRIDE_REDIRECT"
        X11WindowType                      = "SDL_X11_WINDOW_TYPE"
        X11XcbLibrary                      = "SDL_X11_XCB_LIBRARY"
        XinputEnabled                      = "SDL_XINPUT_ENABLED"
        Assert                             = "SDL_ASSERT"
        PenMouseEvents                     = "SDL_PEN_MOUSE_EVENTS"
        PenTouchEvents                     = "SDL_PEN_TOUCH_EVENTS"

    HintPriority* {.size: sizeof(cint).} = enum
        Default
        Normal
        Override

type HintCallback* = proc(user_data: pointer; name, old_val, new_val: cstring) {.cdecl.}

{.push importc, cdecl, dynlib: SdlLib.}
proc SDL_SetHintWithPriority*(name, val: cstring; priority: HintPriority): bool
proc SDL_SetHint*(name, val: cstring): bool
proc SDL_ResetHint*(name: cstring): bool
proc SDL_ResetHints*()
proc SDL_GetHint*(name: cstring): cstring
proc SDL_GetHintBoolean*(name: cstring; default_val: bool): bool
proc SDL_AddHintCallback*(name: cstring; cb: HintCallback; user_data: pointer): bool
proc SDL_RemoveHintCallback*(name: cstring; cb: HintCallback; user_data: pointer)
{.pop.}

{.push inline.}

proc set_hint*(name: Hint; val: string; priority: HintPriority): bool {.discardable.} =
    result = SDL_SetHintWithPriority(cstring $name, cstring val, priority)
    sdl_assert result, &"Failed to set hint ({name}: {val}) with priority '{priority}'"
proc set_hint*(name: Hint; val: string): bool {.discardable.} =
    result = SDL_SetHint(cstring $name, cstring val)
    sdl_assert result, &"Failed to set hint ({name}: {val})"

proc reset*(name: Hint): bool {.discardable.} =
    result = SDL_ResetHint(cstring $name)
    sdl_assert result, &"Failed to reset hint '{name}'"

proc reset_all*() =
    SDL_ResetHints()

proc get_hint*(name: Hint): string                       = $SDL_GetHint(cstring $name)
proc get_bool_hint*(name: Hint; default_val: bool): bool = SDL_GetHintBoolean cstring $name, default_val

proc add_callback*(name: Hint; cb: HintCallback; user_data: pointer = nil): bool {.discardable.} =
    result = SDL_AddHintCallback(cstring $name, cb, user_data)
    sdl_assert result, &"Failed to set callback for hint '{name}'"

proc remove_callback*(name: Hint; cb: HintCallback; user_data: pointer = nil) =
    SDL_RemoveHintCallback cstring $name, cb, user_data

{.pop.}
